data_options:
  data_path: "data"
  w: 0.1
files:
  xml_file: "comp31_sbml.xml"
  bngl_file: "comp31.bngl"
estimation_options:
  est_parms: ["k_LeukB_log","k_LeukBM_log", "kf", "nb", "k4_act","k8_act", "k_tcb", "k4_ex", "k8_ex", "k4_kill","k8_kill", 
              "k4_tox", "k8_tox", "k_adh", "k_migrate_B", "k_migrate_BM", "kf_ifng", "kr_ifng", "kf_il2", "kr_il2", 
              "kf_il6", "kr_il6", "kf_il10", "kr_il10"]
  observables: ["dose", "CD34(a,loc~B)"]
simulation_options:
  # type: "from_python"
  # function: "my_sim.simulate"
  type: "librr_sim" # options: from_bngl and from_python
  stages: # These should be numbers and ordered in order
    0:
      params: 
        kf: 10
        nb: 5
      start: 0   # starting point, assumed 0 if not given
      end:   100 # ending point, assumed 100 if not given
      num:   100 # number of steps, assumed 100 if not given
    1:
      params: 
        kf_il6: 100
      sim_len:   100 # only for 2nd stage and on, fails if not
      num:       100 
    2:
      params: 
        k_migrate_B: 1
        k_migrate_BM: 0.1
        kf_ifng: 10
      sim_len:   100
      num:       100
