data_options:
  data_path: "data"
  w: 0.1
files:
  xml_file: "comp31_sbml.xml"
  bngl_file: "comp31.bngl"
estimation_options:
  est_parms: ["k_LeukB_log","k_LeukBM_log", "kf", "nb", "k4_act","k8_act", "k_tcb", "k4_ex", "k8_ex", "k4_kill","k8_kill", 
              "k4_tox", "k8_tox", "k_adh", "k_migrate_B", "k_migrate_BM", "kf_ifng", "kr_ifng", "kf_il2", "kr_il2", 
              "kf_il6", "kr_il6", "kf_il10", "kr_il10"]
simulation_options:
  type: "librr_sim" # options: from_bngl and from_python
  start: 0   # starting point
  end:   100 # ending point
  num:   100 # number of steps
